version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/banking
      - MONGO_URL=mongodb://mongo:27017
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres
      - mongo
      - rabbitmq
    networks:
      - banking-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=banking
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - banking-network

  mongo:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - banking-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - banking-network
  tests:
    build: .
    depends_on:
      - app
    entrypoint: ["go", "test", "-v"]
    networks:
      - banking-network
      
networks:
  banking-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data: